package tutorial.lorence.admobandroid;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.AdView;
import com.google.android.gms.ads.MobileAds;

public class MainActivity extends AppCompatActivity {

    private AdView mAdView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        /*
         * App ID: ca-app-pub-1527512419709948~5695188817
         * It was generated by Admob Website
         */
        MobileAds.initialize(this, "ca-app-pub-1527512419709948~5695188817");
        mAdView = this.findViewById(R.id.adView);
        AdRequest adRequest = new AdRequest.Builder()
                .addTestDevice(AdRequest.DEVICE_ID_EMULATOR)
                .addTestDevice("BBDEBF183E2BC269C934E07FC05E7F0F")
                .build();
        mAdView.loadAd(adRequest);
    }
}
